### ISSUE TITLE
new taxonomy management interface

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org-rfcs#35]
Problems with the current management ui:
- Taxonomy overview doesn't load: https://de.serlo.org/taxonomy/term/organize-all
- Sorting taxonomy elements doesn't work

Possible solution: create new management interface with already existing views:
- show only two level of taxonomy with taxonomy-view for learners
- move taxonomy like moving a learning object by naming a new parent uuid
- sort taxonomy with the "sort elements" view

**Comment by Entkenntnis** [comment]
ping #58

**Comment by kulla** [comment]
For the long loading of https://de.serlo.org/taxonomy/term/organize-all we have the issue https://github.com/serlo/serlo.org/issues/443 created. With https://github.com/serlo/serlo.org-rfcs/issues/58 this can be closed
